### ISSUE TITLE
Hamaguchi bulk modifications

### ISSUE THREAD

**Issue by phette23** [cca/equella_scripts#34]
https://docs.google.com/spreadsheets/d/1JherZkcsrvVmPfz7Xtd-B2wqxnpfw88kv5F6J4ixzvI/edit?usp=sharing

Find a way to apply the changes from a spreadsheet to EQUELLA now that EBI is defunct. We could modify records using the API or Manage Resources, we should research both methods to see if they're suitable for different use cases. Tools developed can go under utilities/metadata-csv.

We need to map the columns in the spreadsheet back to VAULT metadata fields, see [hamaguchi-map.json](https://github.com/cca/equella_scripts/blob/main/utilities/metadata-csv/hamaguchi-map.json). For the location details for "Move to studio" items, set Location = Printmedia Studio and remove other location details (drawer etc. are not accurate).

For the various color codes and statuses in the spreadsheet, here's what we need to do:

- **Yellow (missing) or Deaccessioned status**: delete record
- **Keep / keep for now / move to studio**: update record
- **Salmon**: new record
- **Green / Blue**: requires research

**Tasks**

- [x] delete removed records
- [x] update records moved to Printmedia Studio
- [ ] create new records - metadata-only, we do not have photos for them
- [ ] update changed records - script is ready but we do not know where in FArchives the prints will go so we cannot complete `mods/location/copyInformation`

**Comment by phette23** [comment]
**Tasks**

- [ ] delete removed records
- [ ] create new records
- [ ] update changed records
